import { Difficulty, Language } from '../models/Problem';

export interface SeedProblem {
  title: string;
  difficulty: Difficulty;
  tags: string[];
  description: string;
  inputFormat: string;
  outputFormat: string;
  constraints: string;
  timeLimit?: number;
  acceptedLanguages?: Language[];
  /** [input, expected output, hidden?] */
  tests: [string, string, boolean?][];
}

export const seedProblems: SeedProblem[] = [
  {
    title: 'Sum of Two Numbers',
    difficulty: 'easy',
    tags: ['math'],
    description: 'Read two integers and print their sum. A good first problem to check that your input parsing works.',
    inputFormat: 'A single line with two integers `a` and `b` separated by a space.',
    outputFormat: 'Print `a + b`.',
    constraints: '-10^9 ≤ a, b ≤ 10^9',
    tests: [['3 5', '8'], ['10 20', '30'], ['-2 7', '5'], ['1000000000 1000000000', '2000000000', true]],
  },
  {
    title: 'Reverse a String',
    difficulty: 'easy',
    tags: ['strings'],
    description: 'Given a string, print it reversed.',
    inputFormat: 'A single line containing the string `s` (no spaces).',
    outputFormat: 'Print `s` in reverse order.',
    constraints: '1 ≤ |s| ≤ 10^5',
    tests: [['hello', 'olleh'], ['world', 'dlrow'], ['a', 'a'], ['racecar', 'racecar', true], ['AlgoArena', 'anerAoglA', true]],
  },
  {
    title: 'Palindrome Number',
    difficulty: 'easy',
    tags: ['math'],
    description: 'Determine whether an integer reads the same backward as forward. Negative numbers are never palindromes.',
    inputFormat: 'A single integer `x`.',
    outputFormat: 'Print `true` if `x` is a palindrome, otherwise `false`.',
    constraints: '-2^31 ≤ x ≤ 2^31 - 1',
    tests: [['121', 'true'], ['-121', 'false'], ['10', 'false'], ['1331', 'true', true], ['0', 'true', true]],
  },
  {
    title: 'Count Vowels',
    difficulty: 'easy',
    tags: ['strings'],
    description: 'Count how many vowels (`a`, `e`, `i`, `o`, `u`) appear in a lowercase string.',
    inputFormat: 'A single line containing a lowercase string `s`.',
    outputFormat: 'Print the number of vowels in `s`.',
    constraints: '1 ≤ |s| ≤ 10^5',
    tests: [['hello', '2'], ['world', '1'], ['aeiou', '5'], ['bcdfg', '0', true], ['programming', '3', true]],
  },
  {
    title: 'Factorial',
    difficulty: 'easy',
    tags: ['math', 'recursion'],
    description: 'Compute `n!`, the product of all positive integers up to `n`. By definition `0! = 1`.',
    inputFormat: 'A single integer `n`.',
    outputFormat: 'Print `n!`.',
    constraints: '0 ≤ n ≤ 20 (the answer fits in a signed 64-bit integer)',
    tests: [['5', '120'], ['0', '1'], ['1', '1'], ['10', '3628800', true], ['20', '2432902008176640000', true]],
  },
  {
    title: 'Fibonacci Number',
    difficulty: 'easy',
    tags: ['dynamic programming', 'recursion'],
    description: 'The Fibonacci sequence is defined as `F(0) = 0`, `F(1) = 1`, and `F(n) = F(n-1) + F(n-2)`. Compute `F(n)`.',
    inputFormat: 'A single integer `n`.',
    outputFormat: 'Print `F(n)`.',
    constraints: '0 ≤ n ≤ 45',
    tests: [['7', '13'], ['0', '0'], ['1', '1'], ['10', '55', true], ['45', '1134903170', true]],
  },
  {
    title: 'Prime Number Check',
    difficulty: 'easy',
    tags: ['math'],
    description: 'Determine whether `n` is a prime number (greater than 1 with no divisors other than 1 and itself).',
    inputFormat: 'A single integer `n`.',
    outputFormat: 'Print `true` if `n` is prime, otherwise `false`.',
    constraints: '1 ≤ n ≤ 10^9',
    tests: [['7', 'true'], ['10', 'false'], ['2', 'true'], ['1', 'false', true], ['999999937', 'true', true]],
  },
  {
    title: 'Greatest Common Divisor',
    difficulty: 'easy',
    tags: ['math'],
    description: 'Find the greatest common divisor of two positive integers.',
    inputFormat: 'A single line with two integers `a` and `b`.',
    outputFormat: 'Print `gcd(a, b)`.',
    constraints: '1 ≤ a, b ≤ 10^9',
    tests: [['12 18', '6'], ['100 25', '25'], ['7 13', '1'], ['81 27', '27', true], ['1000000000 999999999', '1', true]],
  },
  {
    title: 'Binary Search',
    difficulty: 'easy',
    tags: ['binary search', 'arrays'],
    description: 'Given a sorted array of distinct integers and a target value, find the index of the target.',
    inputFormat: 'Line 1: the sorted array, space-separated.\nLine 2: the target.',
    outputFormat: 'Print the 0-based index of the target, or `-1` if it is not present.',
    constraints: '1 ≤ n ≤ 10^5, values fit in a 32-bit signed integer',
    tests: [['1 3 5 7 9\n7', '3'], ['2 4 6\n5', '-1'], ['10\n10', '0'], ['-5 -2 0 3 8 12\n12', '5', true], ['-5 -2 0 3 8 12\n-5', '0', true]],
  },
  {
    title: 'Sort an Array',
    difficulty: 'easy',
    tags: ['sorting', 'arrays'],
    description: 'Sort an array of integers in ascending order. Try implementing a sort yourself before reaching for the built-in one.',
    inputFormat: 'A single line of space-separated integers.',
    outputFormat: 'Print the sorted integers, space-separated.',
    constraints: '1 ≤ n ≤ 10^5, -10^9 ≤ a[i] ≤ 10^9',
    tests: [['5 2 9 1', '1 2 5 9'], ['3 3 1', '1 3 3'], ['42', '42'], ['-1 -5 0 10 -3', '-5 -3 -1 0 10', true]],
  },
  {
    title: 'Valid Parentheses',
    difficulty: 'easy',
    tags: ['stack', 'strings'],
    description:
      'A string of brackets `()[]{}` is valid if every opening bracket is closed by the same type of bracket, in the correct order.',
    inputFormat: 'A single line containing only the characters `()[]{}`.',
    outputFormat: 'Print `true` if the string is valid, otherwise `false`.',
    constraints: '1 ≤ |s| ≤ 10^4',
    tests: [['()', 'true'], ['()[]{}', 'true'], ['(]', 'false'], ['([)]', 'false'], ['{[]}', 'true', true], ['((', 'false', true]],
  },
  {
    title: 'Anagram Checker',
    difficulty: 'easy',
    tags: ['strings', 'hashing'],
    description: 'Two strings are anagrams if one can be rearranged to form the other. Check whether two lowercase strings are anagrams.',
    inputFormat: 'Line 1: string `s`.\nLine 2: string `t`.',
    outputFormat: 'Print `true` if `s` and `t` are anagrams, otherwise `false`.',
    constraints: '1 ≤ |s|, |t| ≤ 10^5',
    tests: [['listen\nsilent', 'true'], ['hello\nworld', 'false'], ['evil\nlive', 'true'], ['abc\ncbaa', 'false', true], ['abc\ncba', 'true', true]],
  },
  {
    title: 'Find Duplicates',
    difficulty: 'easy',
    tags: ['hashing', 'arrays'],
    description: 'Find every value that appears more than once in the array.',
    inputFormat: 'A single line of space-separated integers.',
    outputFormat: 'Print the duplicated values in ascending order, space-separated. Print `-1` if there are none.',
    constraints: '1 ≤ n ≤ 10^5',
    tests: [['1 2 3 2 4 5 1', '1 2'], ['5 6 7 8', '-1'], ['9 9 9 9', '9'], ['1 2 3 4 5', '-1', true], ['4 3 4 3 2', '3 4', true]],
  },
  {
    title: 'Rotate Array',
    difficulty: 'easy',
    tags: ['arrays'],
    description: 'Rotate an array to the right by `k` steps. `k` may be larger than the array length.',
    inputFormat: 'Line 1: the array, space-separated.\nLine 2: the integer `k`.',
    outputFormat: 'Print the rotated array, space-separated.',
    constraints: '1 ≤ n ≤ 10^5, 0 ≤ k ≤ 10^9',
    tests: [['1 2 3 4 5\n2', '4 5 1 2 3'], ['10 20 30 40\n1', '40 10 20 30'], ['7 8 9\n3', '7 8 9'], ['1 2 3 4\n0', '1 2 3 4', true], ['1 2 3 4 5\n7', '4 5 1 2 3', true]],
  },
  {
    title: 'Merge Two Sorted Arrays',
    difficulty: 'easy',
    tags: ['two pointers', 'arrays'],
    description: 'Merge two arrays that are already sorted in ascending order into one sorted array. Either array may be empty.',
    inputFormat: 'Line 1: the first array (may be an empty line).\nLine 2: the second array (may be an empty line).',
    outputFormat: 'Print the merged array, space-separated.',
    constraints: '0 ≤ n, m ≤ 10^5, n + m ≥ 1',
    tests: [['1 3 5\n2 4 6', '1 2 3 4 5 6'], ['10 20\n5 15', '5 10 15 20'], ['1 2 3\n', '1 2 3'], ['\n4 5 6', '4 5 6', true], ['1 1 2\n1 3', '1 1 1 2 3', true]],
  },
  {
    title: 'Remove Duplicates from Sorted Array',
    difficulty: 'easy',
    tags: ['two pointers', 'arrays'],
    description: 'Given a sorted array, remove the duplicates so each value appears only once, keeping the order.',
    inputFormat: 'A single line of space-separated integers in non-decreasing order.',
    outputFormat: 'Print the distinct values, space-separated.',
    constraints: '1 ≤ n ≤ 10^5',
    tests: [['1 1 2 3 3', '1 2 3'], ['1 2 3 4', '1 2 3 4'], ['2 2 2 2', '2'], ['1', '1', true], ['-3 -3 0 0 0 7', '-3 0 7', true]],
  },
  {
    title: 'Matrix Transpose',
    difficulty: 'easy',
    tags: ['matrix', 'arrays'],
    description: 'Print the transpose of an `r × c` matrix: row `i` of the output is column `i` of the input.',
    inputFormat: 'Line 1: `r` and `c`.\nNext `r` lines: `c` integers each.',
    outputFormat: 'Print `c` lines with `r` space-separated integers each.',
    constraints: '1 ≤ r, c ≤ 500',
    tests: [['2 2\n1 2\n3 4', '1 3\n2 4'], ['3 2\n1 2\n3 4\n5 6', '1 3 5\n2 4 6'], ['1 1\n7', '7'], ['2 3\n1 2 3\n4 5 6', '1 4\n2 5\n3 6', true]],
  },
  {
    title: 'First Peak Element',
    difficulty: 'easy',
    tags: ['arrays'],
    description:
      'An element is a peak if it is strictly greater than its neighbours (elements at the ends only have one neighbour). Adjacent elements are always different. Find the first peak.',
    inputFormat: 'A single line of space-separated integers.',
    outputFormat: 'Print the 0-based index of the first peak.',
    constraints: '1 ≤ n ≤ 10^5, a[i] ≠ a[i+1]',
    tests: [['1 2 3 1', '2'], ['1 2 1 3 5 6 4', '1'], ['5 4 3 2 1', '0'], ['7', '0', true], ['1 2 3 4 5', '4', true]],
  },
  {
    title: 'Two Sum',
    difficulty: 'medium',
    tags: ['hashing', 'arrays'],
    description:
      'Given an array of integers and a target, find indices `i < j` such that `a[i] + a[j] = target`. If several pairs work, choose the one with the smallest `i`, and then the smallest `j`.',
    inputFormat: 'Line 1: the array, space-separated.\nLine 2: the target.',
    outputFormat: 'Print `i` and `j` separated by a space. A valid pair always exists.',
    constraints: '2 ≤ n ≤ 10^4, -10^9 ≤ a[i], target ≤ 10^9',
    tests: [['2 7 11 15\n9', '0 1'], ['1 2 3 4\n5', '0 3'], ['3 2 4\n6', '1 2'], ['3 3\n6', '0 1', true], ['5 1 5 1\n6', '0 1', true]],
  },
  {
    title: 'Maximum Subarray',
    difficulty: 'medium',
    tags: ['dynamic programming', 'arrays'],
    description: 'Find the contiguous, non-empty subarray with the largest sum and print that sum.',
    inputFormat: 'A single line of space-separated integers.',
    outputFormat: 'Print the maximum subarray sum.',
    constraints: '1 ≤ n ≤ 10^5, -10^4 ≤ a[i] ≤ 10^4',
    tests: [['-2 1 -3 4 -1 2 1 -5 4', '6'], ['1', '1'], ['5 4 -1 7 8', '23'], ['-1 -2 -3 -4', '-1', true]],
  },
  {
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'medium',
    tags: ['sliding window', 'strings', 'hashing'],
    description: 'Find the length of the longest substring that contains no repeated characters.',
    inputFormat: 'A single line containing the string `s` (no spaces).',
    outputFormat: 'Print the length of the longest such substring.',
    constraints: '1 ≤ |s| ≤ 10^5',
    tests: [['abcabcbb', '3'], ['bbbbb', '1'], ['pwwkew', '3'], ['dvdf', '3', true], ['abcdefg', '7', true]],
  },
  {
    title: 'Longest Palindromic Substring',
    difficulty: 'medium',
    tags: ['strings', 'dynamic programming'],
    description: 'Find the longest substring that is a palindrome. If several have the maximum length, print the one that starts first.',
    inputFormat: 'A single line containing the string `s` (no spaces).',
    outputFormat: 'Print the longest palindromic substring.',
    constraints: '1 ≤ |s| ≤ 1000',
    tests: [['babad', 'bab'], ['cbbd', 'bb'], ['a', 'a'], ['ac', 'a', true], ['forgeeksskeegfor', 'geeksskeeg', true]],
  },
  {
    title: 'Longest Common Subsequence',
    difficulty: 'medium',
    tags: ['dynamic programming', 'strings'],
    description: 'Find the length of the longest subsequence common to two strings. A subsequence keeps the order of characters but may skip some.',
    inputFormat: 'A single line with two strings separated by a space.',
    outputFormat: 'Print the length of their longest common subsequence.',
    constraints: '1 ≤ |a|, |b| ≤ 1000',
    tests: [['abcde ace', '3'], ['abc abc', '3'], ['abc def', '0'], ['AGGTAB GXTXAYB', '4', true]],
  },
  {
    title: 'Coin Change',
    difficulty: 'medium',
    tags: ['dynamic programming'],
    description: 'Given coin denominations (unlimited supply of each) and an amount, find the fewest coins needed to make the amount.',
    inputFormat: 'Line 1: number of denominations `n`.\nLine 2: the `n` denominations.\nLine 3: the amount.',
    outputFormat: 'Print the minimum number of coins, or `-1` if the amount cannot be made.',
    constraints: '1 ≤ n ≤ 12, 1 ≤ coin ≤ 2^31 - 1, 0 ≤ amount ≤ 10^4',
    tests: [['3\n1 2 5\n11', '3'], ['2\n2 5\n3', '-1'], ['1\n2\n0', '0'], ['4\n1 2 5 10\n27', '4', true]],
  },
  {
    title: 'Subset Sum',
    difficulty: 'medium',
    tags: ['dynamic programming'],
    description: 'Determine whether some subset of the given positive integers adds up exactly to the target.',
    inputFormat: 'Line 1: `n`.\nLine 2: `n` positive integers.\nLine 3: the target.',
    outputFormat: 'Print `true` if such a subset exists, otherwise `false`.',
    constraints: '1 ≤ n ≤ 100, 1 ≤ a[i] ≤ 1000, 1 ≤ target ≤ 10^4',
    tests: [['3\n1 2 3\n5', 'true'], ['4\n2 4 6 10\n16', 'true'], ['3\n1 2 5\n4', 'false'], ['5\n1 3 5 7 9\n8', 'true', true], ['3\n2 4 6\n5', 'false', true]],
  },
  {
    title: '0/1 Knapsack',
    difficulty: 'medium',
    tags: ['dynamic programming'],
    description: 'Each item has a weight and a value and can be taken at most once. Maximise the total value without exceeding the capacity.',
    inputFormat: 'Line 1: `n` and capacity `W`.\nNext `n` lines: weight and value of each item.',
    outputFormat: 'Print the maximum total value.',
    constraints: '1 ≤ n ≤ 100, 1 ≤ W ≤ 10^4',
    tests: [['3 50\n10 60\n20 100\n30 120', '220'], ['1 10\n5 10', '10'], ['2 5\n6 10\n7 20', '0'], ['4 7\n1 1\n3 4\n4 5\n5 7', '9', true]],
  },
  {
    title: 'Word Ladder',
    difficulty: 'hard',
    tags: ['graphs', 'bfs', 'strings'],
    description:
      'Transform `begin` into `end` by changing one letter at a time; every intermediate word (and `end`) must be in the word list. Find the number of words in the shortest transformation sequence, including `begin` and `end`.',
    inputFormat: 'Line 1: `begin`.\nLine 2: `end`.\nLine 3: the word list, space-separated.',
    outputFormat: 'Print the length of the shortest sequence, or `0` if no sequence exists.',
    constraints: 'All words have the same length (1–10) and are lowercase; the list has at most 5000 words.',
    tests: [['hit\ncog\nhot dot dog lot log cog', '5'], ['hit\ncog\nhot dot dog lot log', '0'], ['a\nc\na b c', '2'], ['red\ntax\nted tad tax', '4', true]],
  },
  {
    title: 'N-Queens Count',
    difficulty: 'hard',
    tags: ['backtracking', 'recursion'],
    description: 'Count the ways to place `n` queens on an `n × n` chessboard so that no two queens attack each other.',
    inputFormat: 'A single integer `n`.',
    outputFormat: 'Print the number of distinct solutions.',
    constraints: '1 ≤ n ≤ 10',
    tests: [['4', '2'], ['1', '1'], ['8', '92'], ['6', '4', true], ['10', '724', true]],
  },
  {
    title: 'Shortest Paths (Dijkstra)',
    difficulty: 'hard',
    tags: ['graphs'],
    description:
      'Given a weighted, undirected graph as an adjacency matrix (0 means no edge), find the shortest distance from the start node to every node.',
    inputFormat: 'Line 1: `n`.\nNext `n` lines: `n` non-negative integers each (the matrix).\nLast line: the start node.',
    outputFormat: 'Print `n` distances, space-separated. Print `-1` for unreachable nodes.',
    constraints: '1 ≤ n ≤ 200, 0 ≤ weight ≤ 1000',
    tests: [
      ['4\n0 1 4 0\n1 0 2 6\n4 2 0 3\n0 6 3 0\n0', '0 1 3 6'],
      ['3\n0 5 0\n5 0 0\n0 0 0\n0', '0 5 -1'],
      ['1\n0\n0', '0'],
      ['5\n0 2 0 6 0\n2 0 3 8 5\n0 3 0 0 7\n6 8 0 0 9\n0 5 7 9 0\n0', '0 2 5 6 7', true],
    ],
  },
  {
    title: 'Median of Two Sorted Arrays',
    difficulty: 'hard',
    tags: ['binary search', 'arrays'],
    description: 'Find the median of the combined elements of two sorted arrays. Aim for O(log(n + m)).',
    inputFormat: 'Line 1: the first sorted array.\nLine 2: the second sorted array.',
    outputFormat: 'Print the median with exactly one digit after the decimal point.',
    constraints: '1 ≤ n, m ≤ 10^5',
    tests: [['1 3\n2', '2.0'], ['1 2\n3 4', '2.5'], ['0 0\n0 0', '0.0'], ['2\n1 3', '2.0', true], ['1 5 9\n2 3', '3.0', true]],
  },
  {
    title: 'Sudoku Solver',
    difficulty: 'hard',
    tags: ['backtracking'],
    description: 'Solve a 9 × 9 Sudoku. Empty cells are written as `0`. Each puzzle has exactly one solution.',
    inputFormat: 'A single line of 81 digits, row by row.',
    outputFormat: 'Print the solved grid as a single line of 81 digits.',
    constraints: 'The puzzle is valid and uniquely solvable.',
    timeLimit: 2000,
    tests: [
      [
        '530070000600195000098000060800060003400803001700020006060000280000419005000080079',
        '534678912672195348198342567859761423426853791713924856961537284287419635345286179',
      ],
      [
        '003020600900305001001806400008102900700000008006708200002609500800203009005010300',
        '483921657967345821251876493548132976729564138136798245372689514814253769695417382',
      ],
      [
        '123456789456789123789123456231564897564897231897231564312645978645978312978312645',
        '123456789456789123789123456231564897564897231897231564312645978645978312978312645',
        true,
      ],
    ],
  },
];
